### ISSUE TITLE
BE: Field "Jahr" is not necessary

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#1]
In the BE from the item there is a field called "Jahr". This is not needed. Please remove this field. 

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/22646070/babebba4-ec6a-11e6-85b9-a7811d1eff28.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

As per the specification doc, the frontend 'Jahr' filter uses this field. 
So if we remove it from the backend then how this field will gets filled from frontend? Can you please guide us more here?

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
That's like it is described in Specs: The field "Entscheiddatum" is a date which is mandatory in the BE. This date is used for filtering the FE output for the years :-)

So the field "Jahr" that you added is not used in the BE (because you got already a field called "Entscheiddatum" which is a date field. It is just used in the FE for filtering the the single items with year.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Screenshot**: http://www.awesomescreenshot.com/06a68qet7f

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. That's correct.

Thanks.
