### ISSUE TITLE
Inserting a PDF file from fileadmin listing view as shown in printscreen is not possible in BE

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#10]
In the BE of the DOKUMENTE we can not insert a file which leads in the fileadmin folder. There is only a field for inserting images. Please remove in the marked field the upload for images due to on the displayed field there were only PDF documents we will upload. 

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/22929658/0d449756-f2bd-11e6-8ea3-3e6e782d25ce.png)

Can you please fix that?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status:** Done
**Screenshot:** http://prntscr.com/e9c5mc

Regards.
Thank you.

**Comment by angeloprevitali** [comment]
Hello Jignesh
great, thanks. Works.

Regards,
Angelo
