### ISSUE TITLE
Incompatibility of extension with TYPO3 8.6

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#11]
Hello Jignesh

as you wrote that the extension works with 8.6 I installed it on the DEV server of t8.edorf.ch for testing purposes. Now on this dev server there is coming a fatal error by installing this extension.

https://github.com/NetConsultAG/netc_adresslist/issues/6

Can you check and fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

**#Typo3 8.6 Compatibility**
We have checked the compatibility with TYPO3 8.6 now it's working all fine with this. You can pull all the latest files from here: https://github.com/NetConsultAG/netc_ubidb

Don't hesitate to ask if you have any queries.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Thanks. 

Regards,
Angelo
