### ISSUE TITLE
Paging not working

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#12]
Hello Jignesh

the paging on the dev server is not working. There is an blank page coming and the following error occurs:

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Can you fix that as soon as possible?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

**#Pagnig not working**
**Status**: Done
**Screenshot**: http://prntscr.com/ef0mb8

Please review this from your end and let's know if there is still any problem or query from your end.
Regards!

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. That works fine.

Regards,
Angelo
