### ISSUE TITLE
"Results and sort area" disappears after moving on in pagination

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#13]
Hi

On this page:
http://dev.kommission.netconsult.ch/de/themen/ubi-datenbank/

1. After you submit the form "Filtern" to get results you see on top the section "Resultate" with the option to sort the results.

2. Now you click page "2" in the pagination

3. After page "2" loads, the area "Resultate" with the option to sort the results disappears.

See here:
![resultate](https://cloud.githubusercontent.com/assets/1160557/23605778/542325ba-025e-11e7-8aa3-a7146f0c3ddb.gif)

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

#Results and sort area disappears after moving on in pagination
**Status:** Done
**Screencast:** http://recordit.co/TseQnOTPJj

Please also review from your end and confirm the same.

Regards.
Thank You.
