### ISSUE TITLE
Sorting field doesn't work

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#14]
The sorting field doesn't change anything after chosing any sorting criteria.

1. Submit the form with "Filtern" to get results listed
2. Chose in the area "Resultate" the select box to change the sorting order
3. Nothing changes in the list

See here:
![sort](https://cloud.githubusercontent.com/assets/1160557/23605935/e6c5d9d0-025e-11e7-8a3e-ece7f32d08ae.gif)

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

Thank you for your message. We will update you before this weekend.

Have a nice day ahead. Regards!

**Comment by michelrossier** [comment]
Hi Jignesh
Thanks, that is perfect. Have a good day as well!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Evening!

Due to some workload, we won't be able to complete your last feedback in this week. So we will update you by the middle of next week for both of your feedback points. I hope it would be fine for you.

Have a nice day ahead.

Regards.
Thank You.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Evening!

We have got some time in between so we have resolved your last mentioned issues. Please find our update as following.

#Sorting field doesn't work
**Status:** Done
**Screencast:** http://recordit.co/vnzTmjDVoq
**Comment:** You can check the working of sorting here: http://dev.kommission.netconsult.ch/de/themen/ubi-datenbank/

**Note:** It seems you guys have done some changes at dev server: http://dev.kommission.netconsult.ch/de/themen/ubi-datenbank/ But not updated in the git repository
Can you please update the Git Repository? So we can also update the repository.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

I updated the Github Verson with our version. 
So you can update the repository as requested.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

As you have added all your code from the Dev server, All our last change also been updated at the same time. So we don't have to do anything for now.

Have a nice day ahead.
Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 19. März 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 20. März 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
