### ISSUE TITLE
Reset button error pulldown fields

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#15]
Hello Jignesh

we found a little bug: If you reset the form all fields in the filter gets resetted correctly. Apart of all pulldowns: Those are not resetted to the initial value.

Can you please fix this issue?

Thanks.

Regards,
Angelo

![reset](https://cloud.githubusercontent.com/assets/17588253/24347653/48d9dc4a-12d9-11e7-8603-7b4456552170.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have checked this issue, It seems you have enabled the plugin for select box, that is not refreshing when clicking on the reset button. If you check by removing the Plugin, Then you can find there is not any issue. 
So please reset the selection of the select box while clicked on the reset button (id=reset). Then it would not have any issue.

Let's know your reply for the same.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

can you please explain me a little better what you mean exactly? I do not understand what you mean..

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!
Please find our reply as below.

You have used the third party jquery select box plugin, that makes the select box by cloning the options of select box into ul li tags - http://prntscr.com/epcn5b
Our logic updates values of the select box properly when filtering and resetting the form.
But the third party jquery plugin cannot update its values of ul li tags automatically, So you need to reinitialize those on such events like reset, filter etc.

If you want to resolve this issue by us then you have to provide us the function which is used to initialize the plugin, so we can add it in our logic.

Don't hesitate to ask if you have any questions.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

we updated the reset button with own functions to reload the form again to work for.

So this issue can be closed.

Regards,
Angelo
