### ISSUE TITLE
Sorting results does not gets applied in filter search

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#16]
Hello

If you filter some criteria and click for search the results gets correctly sorted by the pulldown choice named "sortierung". If you change the sorting option on the results page the same sorting option which leads in the filter form gets not adapted with the new sorting value from the result page. By applying the sorting option on the search results the sorting value should change also in the filter form.

Can you fix this little bug?

Thank you very much.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

This is also one of the side effects of the Select Box, See our last comment here: https://github.com/NetConsultAG/netc_ubidb/issues/15#issuecomment-289431882

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

can you please adapt the the function with your logic which is used to initialize the plugin with 

> $("select").chosen();

Thanks for your work and feedback.

Reagrds,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status:** Done
**Screencast:** http://recordit.co/cTjGWytUhP
**Comment:** We have fixed this bug, now the selected sorting items also change in the filter form. 

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 2. April 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 3. April 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Ernest Peter (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks. That works. I close this ticket now.

Regards,
Angelo
