### ISSUE TITLE
Search function not working due to unknown error

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#17]
Hello Jignesh

we realised that the search form is not working anymore.

Can you please have a look to this and give us feedback?

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/24490527/3ba454aa-1523-11e7-90d7-751ce333defb.png)

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have checked this issue, It seems there are too many fields in the query for that particular textbox, Which results into longer time for the processing. So it gives **500 Internal Server Error** Can you try to give minimal fields for that box? It will give faster results too.

Waiting for your reply here.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

what daes it mean? What do you mean exactly? the search fields should be as they are in the default descritpion of https://github.com/NetConsultAG/netc_ubidb/issues/5.

Thanks for your feedback.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your reply. 

Status: Done
Screenshot: http://prntscr.com/es6ax5
Comment: Yes, We have missed this, Now It will search from the following fields from the mentioned document tables. 
-------
entscheidnr
beschreibung
entscheiddatum
medienmitteilung
medienmitteilungUrl
publikation
publikationUrl
bundesentscheid
bundesentscheidUrl
-------

Please review this and share your feedback with us.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. It works fine.

Regards,
Angelo
