### ISSUE TITLE
Search result sum of found results are wrong

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#18]
Hello Jignesh

the sum number of found results are wrong. There are always 10 instead of the exact count of found results. I think that this number 10 looks like the number of items per page which is definied by constants.. but i am not shure about that.

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/24500322/346fc382-1545-11e7-913d-3a727371f19f.png)

Can you fix that?

Thank you.

Best reagrds,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Screencast**: http://recordit.co/vd0yo0y5TK

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks. That works now perfect.

I will close this ticket now.

Regards,
Angelo
