### ISSUE TITLE
Task/Change request EXT:netc_ubidb - Showing field in BE Layout and sorting in list 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#19]
1.) In the EXT:netc_ubidb in the BE in list view in "Entscheid-Dokument" (see printscreen 1) in the view of a single item in the tab "Eigenschaften (see printscreen 2) there are some little changes we need to have:

a) The listing in the field "Bestimmung" > "Verfügbare Objekte:" must be sorted as default as Alphanumeric ASC (see printscreen 3)

b) The single items of this field MUST have additionaly the field of the table "recht" after the name of the item added like (xyz) (see printscreen 4). The field which has to be displayed is located from the table "recht" (see printscreen 5, where it leads).

Regards,
Angelo

![1](https://cloud.githubusercontent.com/assets/17588253/25218164/1d86f2b0-25aa-11e7-9d5c-1019fd1c00bb.png)
![2](https://cloud.githubusercontent.com/assets/17588253/25218161/1d86162e-25aa-11e7-9884-05288d0a627a.png)
![3](https://cloud.githubusercontent.com/assets/17588253/25218165/1d8cdd60-25aa-11e7-91cd-1da5b718ab1e.png)
![4](https://cloud.githubusercontent.com/assets/17588253/25218162/1d861c32-25aa-11e7-89a9-126a76bbcabc.png)
![5](https://cloud.githubusercontent.com/assets/17588253/25218163/1d86a54e-25aa-11e7-8fe7-561a515037d3.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Let's check those issue we will get back to you soon.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Please find our update as following.

**1.** In the EXT:netc_ubidb in the BE in list view in "Entscheid-Dokument" (see printscreen 1) in the view of a single item in the tab "Eigenschaften (see printscreen 2) there are some little changes we need to have:
**Status:** Done
**Screenshot:** http://recordit.co/hd6X8Qhrvj

**A).** The listing in the field "Bestimmung" > "Verfügbare Objekte:" must be sorted as default as Alphanumeric ASC (see printscreen 3)
**Status:** Done
**Screenshot:** http://prntscr.com/ez3h57

**B).** The single items of this field MUST have additionaly the field of the table "recht" after the name of the item added like (xyz) (see printscreen 4). The field which has to be displayed is located from the table "recht" (see printscreen 5, where it leads).
**Status:** Done
**Screenshot:** http://prntscr.com/ez3el9

Please review this from your end share your feedback with us.

**Note:** We have spent 3 Hours on this. Please confirm from your end too.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. That looks good. 

The three hours are ok.

Regards,
Angelo
