### ISSUE TITLE
BE: Id of current ID of item + 1 not working in document

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#2]
In the screen there is a filed called "Entscheid-Nr". This field must have the inital value like described in the specs. Currently if you add a new record there is alwyas the same value in there. So if the first ID of the new item is i.e. 45 a new record must have the initial value of b.46 and so on. Please refer to the printscreen and the specs.

![screenshot_2](https://cloud.githubusercontent.com/assets/17588253/22646186/4dc69d68-ec6b-11e6-8088-0f42842ba08c.png)
![be-a-id](https://cloud.githubusercontent.com/assets/17588253/22646195/5de1a832-ec6b-11e6-9cf3-bb0a3d30266e.jpg)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Status: Done
Screencast: http://recordit.co/SvlVPr9MV1
Comment: We have tried the possible solution from Page TSConfig - http://awesomescreenshot.com/05568l1590, but it is not working for a backend. After adding a record, you need to clear system cache and then add a new record. It will work.

Please review this from your end and share your feedback with us.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. Now it works correctly (if you clean out the cache).

We see the problem. Let it be as we saw that this is a neverending problem in TYPO3 CMS verison 6.2. From the version of 8.6 this issue is fixed and will work already correctly as I read now. The code will be to insert the clearCache.all in the BE user TS options.
