### ISSUE TITLE
Bug in results page with pagination 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#20]
Hello Jignesh

we found a little bug on the EXT:netc_ubidb. If you want to jump to another page in results the page gets stuck in the buttom of the page instead of returning to the top of the page. Can you please fix this issue asap?

![paging](https://cloud.githubusercontent.com/assets/17588253/25235822/94ffa17a-25e6-11e7-841d-497ffbbc35c0.png)

Thanks in advance for your work.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://recordit.co/r3ChoSWfaX
Comment: Please review this from your end too.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 23. April 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 24. April 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
Hello Jignesh

works, thanks.

Regards,
Angelo
