### ISSUE TITLE
Flexform Dokument, Tab "Eigenschaften" and Field "Bestimmung"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#22]
Hello Jignesh

we still found an little bug in the actual EXT:netc_ubidb.

Position: Flexform Dokument, Tab "Eigenschaften", Field "Bestimmung"
The source must be the table "netc_ubidb_domain_model_best_absatz"

![grafik](https://cloud.githubusercontent.com/assets/17588253/25839657/e14d84e6-3498-11e7-81cd-185f78be8193.png)

In field "best_absatz" must be saved the values of uid from the table "netc_ubidb_domain_model_best_absatz" (not "netc_ubidb_domain_model_bestimmung")

The view of the source is like in the list view from "Bestimmung/Absatz" (column "Bestimmung"):

![grafik](https://cloud.githubusercontent.com/assets/17588253/25839680/f6525c36-3498-11e7-9f37-6e12821e3e2d.png)

Could you please fix that on the dev plattform?

Thanks for your work!

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

We will check this issue in this week and try to give you update. Regards!

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status:** Done
**Screenshots:** http://prntscr.com/f64a9f, http://prntscr.com/f64f2f, http://prntscr.com/f64d1m

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks for your message.

I am sorry, but all the changes you made are completely wrong. so, please revert all the things you did. 

Here we try to explain again in a different way, how exactly you should adapt the extension.

#1: The new added field in the mySQL DB please remove it like in followed printscreen.
![database-table-recht](https://cloud.githubusercontent.com/assets/17588253/25892433/aac8e6f4-3574-11e7-8b83-baa697fd4f9a.gif)

#2: Please delete the added field "recht" in FLEXFORM (see printscreen)
![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/25892494/d170ab20-3574-11e7-9158-0edb2b7db6ec.png)

#3: In the list view the view should be like before (see screenshot)
![screenshot_2](https://cloud.githubusercontent.com/assets/17588253/25892528/ed0da37e-3574-11e7-8f95-830011cefbfe.gif)

#4: Next: The changes as we need. In the Flexform of the http://prntscr.com/f64t40. See description in printscreens AND in the PDF.
![unbenannt-4](https://cloud.githubusercontent.com/assets/17588253/25893023/989e5d72-3576-11e7-94fb-90514a2ed61e.gif)

[netc_ubidb_bugreport_20170508.pdf](https://github.com/NetConsultAG/netc_ubidb/files/989375/netc_ubidb_bugreport_20170508.pdf)

We hope you understand the thing. Otherwise please SKYPE me or sende me a Mail if there were some things still unclear.

Thanks for your work.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message. let's revert last changes. We will get back to you if have any queries. 

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

Please find our comments as below.

According to this ticket https://github.com/NetConsultAG/netc_ubidb/issues/19 point 'B', you have asked to have a field 'recht_de' label here ( https://cloud.githubusercontent.com/assets/17588253/25218162/1d861c32-25aa-11e7-89a9-126a76bbcabc.png) instead of the numbers. The source table of that field is was the 'best_absatz' table and the labels were like 'Bestimmung, Absatz', but solve this issue, We had changed the source table to the 'Bestimmung' because you need 'Recht_de' field in the label.

Now in this ticket, you reported a bug for the source table, and you still want the 'best_absatz' table as the source, but needs 'recht_de' field of 'recht' table in the label. 

So we have added a field of 'recht' table in 'best_absatz' table. 

So the solution of the https://github.com/NetConsultAG/netc_ubidb/issues/19 will be affected here. It seems both tickets conflicts here.
So can you please guide us here more that what we should follow here?

Looking forward to having a response from your side.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

i think we bough have a understanding problems here. Please restore all work you done from this ticket to the old version as described so we got the old start for all of us. Afterhtat we will retry to re-explain it in a different way.

Can you please do that and confirm me the undo?

Thank you very much for your work.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

I hope you had a nice weekend. Thanks for your message. 

We have reverted back the last changes related to this ticket. See this screenshot: http://prntscr.com/f7yha6

We will wait for your reply on the exact changes that we would be needed.

Regards.
Thank you

**Comment by angeloprevitali** [comment]
Good morning Jignesh

thank you. But now we can not se the frontend anymore from the old version on http://dev.kommission.netconsult.ch/de/themen/ubi-datenbank/. 

As soon you fixed this we will redefine the changes again.

Thank you .

Regards,
Angelo.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thanks for the notification.

Yes, we have also corrected that. You can now check it.  Regards!

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks, but as we see there is still a field that isn't needed from the changes: tx_netcubidb_domain_model_bestabsatz.recht

Are you really shure that everything is reverted?

It seems that some things aren't still reverted.

Thanks for REcheck the changes again.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thanks for your message.

It seems it's the problem of DB. Can you please check it now? Sorry for asking you to check multiple times.

Regards.

**Comment by angeloprevitali** [comment]
I will open new tickets concerning new works on this extension and new change requests. So i close this ticket.

Regards,
Angelo
