### ISSUE TITLE
Broken extension message in install tool EXT:netc_ubidb

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#23]
Hello Jignesh

we found out that the existing EXT:netc_ubidb gets a broken message in the install tool. See printscreen from install tool on website dev.kommission.netconsult.ch (you got all the access data already). 

![screenshot_1](https://user-images.githubusercontent.com/17588253/26927643-035f8774-4c53-11e7-992f-2a9a37019cef.png)

We found out that the problem leads in the following part of getEntschidnr in BackendService.php code:

![grafik](https://user-images.githubusercontent.com/17588253/26927691-31bcc50a-4c53-11e7-97a4-c2e2d9d11230.png)

If we deactive the EXT:netc_ubidb in the Extension Manager the message disappears. 

Can you please fix this issue as soon as possible and inform us.

I assume that the whole extension is still TYPO3 CMS version 8.7 comform, right? As in the em_conf.php-file is written that it is compatible with the version 6.2.0-8.9.99.

PLEASE do **NOT** upload the changed and adpted version of the extension on GitHub after fixing this. We will have to make a versioning of this extension after this problem is fixed by you.

Due to i will be in holidays until 18/06/17 i will not be able to answer any questions about this issue. I hope that you can fix this without any further questions in the emantime.

Thank you very much for your help and work.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

Let's check this and we will get back to you.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 18. Juni 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 19. Juni 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prntscr.com/fhrsri

**Note:** We haven't uploaded it to the repository. 

Have a nice day and a great weekend ahead.
Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. But the problem still exists: The EXT:netc_ubidb looks still broken (TYPO3 in the install tool says that the extension could NOT be loaded correctly. See printscreen).

![screenshot_1](https://user-images.githubusercontent.com/17588253/27272830-955a2658-54cc-11e7-8e89-6b34377be300.png)

Can you please fix this urgently?

Thanks for your feedback.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message. 

Can you please let's know, In which server you are testing? Here: http://dev.kommission.netconsult.ch/

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

YES, on http://dev.kommission.netconsult.ch/, correct.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
@angeloprevitali  Thank you for your quick reply.
Okay, Let's check this. We will get back to you soon.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Screenshot**: http://prntscr.com/fliv1u

**Note:** All the latest files are on this server: http://dev.kommission.netconsult.ch

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

it is still not working, yet. 

Reason: You adapted it on another website then described. PLEASE check the correct URL: http://dev.kommission.netconsult.ch! We are all working on this domain.

Can you please fix it on the correct website?

Thanks.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello Angelo
Greetings of the day.

We have checked the issue in depth. It seems there is a strange issue with TYPO3 6.2.X. You know, as per our requirement for the "entscheidnr" field, It should be prefilled with 'b.(last uid+1)'. So to accomplish this we have to use TCA for DataBase preprocessing. So, When install tool checks the extension compatibility it tries to load the TCA of all the extension tables. But at that time it doesn't find the proper processing results so it goes in the infinite process and just shows the Loading image on the screen. 
Although, It doesn't break any of the functionality in the Backend as well as Frontend. All seems working perfectly fine. 

But at the same time, it works in the latest TYPO3 versions i.e. 8.X. So maybe its the compatibility issue. We have tried to find out the reason, But not able to find the exact problem 

Can you please ask your team to help us to find out the issue here?

Just question, Is it really needed? If no then we can ignore this and save time (As you know, functionality is working fine.)

Please let's know your reply on this.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks for your message. 

So we exported the actual extension EXT:netc_ubidb from the TYPO3 CMS version 6.2 on the  dev.kommission.netconsult.ch website and imported it on a TYPO3 CMS version 8.7.1. The installation is not working on a V8.7. the following error occures:

![ubidb-export2](https://user-images.githubusercontent.com/17588253/27424842-baf51f8c-5736-11e7-8845-0b7da0cff27f.png)

![ubidb-export1](https://user-images.githubusercontent.com/17588253/27424857-c6ceb7a0-5736-11e7-8363-55627651b640.png)

Can you please fix the extension on dev.kommission.netconsult.ch like this that we can install the extension on a TYPO3 CMS version 8.7.1?

Can you fix that urgently? Would be great! Thanks.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Greetings of the day!

Thank you for your message. Let's check this. We will get back to asap.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

It seems there is not any problem with the developed extension. We have noticed there is some problem with TYPO3 core. So we have found a solution for it. Please see attached file. So, Can you please replace the attached file to this location: typo3_src-8.7.1/typo3/sysext/extensionmanager/Classes/Utility/InstallUtility.php
[InstallUtility.zip](https://github.com/NetConsultAG/netc_ubidb/files/1094627/InstallUtility.zip)

**Note:** Please unzip the file.

Then after please perform below steps to ensure all working fine.

Step-1. Remove the extension entry from the PackageStates.php file
Step-2. Try to install extension again

Please let's know your feedback on this too.
Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks. Strange thing: it worked with your adapted file from the core of T3...

Regards,
Angelo
