### ISSUE TITLE
Bug: Missing value of year by saving field in BE

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#24]
If you enter a brandnew item in the BE the field Entscheiddatum in a new document (Dokumente) it must have the year filled out and saved in to netc_ubidb_domain_model_dokument.yahr from the date entered of netc_ubidb_domain_model_dokument.entscheiddatum. See printscreen.

![unbenannt-1](https://user-images.githubusercontent.com/17588253/27643369-24f55a7a-5c21-11e7-85b5-f54f501c100f.jpg)

![db](https://user-images.githubusercontent.com/17588253/27677183-0b8e331e-5cb1-11e7-923b-e828e62de847.jpg)

Please make those changes ONLY in the EXT:netc_ubidb on the following DEV server located on http://dev.kommissionv8.netconsult.ch and after that DO NOT upload the adapted files on GitHub.

You got received the new access data by mail today.

PLEASE, if you got questions about this task do SKYPE me. 

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

We would like to you ask you a question here. Fyi, For the Front End Filter form, we have managed this Year field dynamically by extracting it from the 'entscheiddatum'. So, ultimately it would be the same effect. So do you still want to go with your mention point or we should leave it as it is for now?

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

"For the Front End Filter form, we have managed this Year field dynamically by extracting it from the 'entscheiddatum'"
**Answer:** That is correct.

"So do you still want to go with your mention point?"
**Answer:** YES, please. Adapt it like described. We know that there will be no effect on the FE. But we must have this year in the DB as described.

Thanks for your work.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Screenshot**: http://prntscr.com/fuqof8

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

this one still does not work correctly: If you save a NEW OR AN EXISTING Item im Entscheid-Dokument, the field "YEAR" gets still NOT saved in the DB. It has to be saved automatically depending on the field "Entscheiddatum" (see printscreen).

![screenshot_3](https://user-images.githubusercontent.com/17588253/28157471-ea82e8f2-67b6-11e7-805a-45e9b0609091.png)

![unbenannt-1](https://user-images.githubusercontent.com/17588253/28157480-f100fc5a-67b6-11e7-9b55-0d766135a7dd.jpg)

Thanks for the fix.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message. Can you please let's know where exactly you are testing this?

Waiting for your response here. Regards!

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 16. Juli 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 17. Juli 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
Hello Jignesh

we are testing always on the same DEV plattform as described - on http://dev.kommissionv8.netconsult.ch.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you very much for your message. Yes, let's check this issue.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

#Remove Mandatory constraint
**Status**: Done
**Screenshot**: http://prntscr.com/fx25ql

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

The mandatory field in the BE is now ok. BUT if you save the form the YEAR gets NOT saved in the field "Jahr" in the database. It is still empty. See printscreen https://user-images.githubusercontent.com/17588253/28157548-2795f0b8-67b7-11e7-9180-332045a9ceb0.jpg. 

Can you please fix that?

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

We have added one condition for the field, That if the Date (Jahr) field is edited/changed then and only then it should automatically save the field. So, you have to edit and change the field for old records to see the change.
Fyi, For the new records, it will work fine.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

we tested this. It works. Thanks. Everything is fine.

Regards,
Angelo
