### ISSUE TITLE
Changing Version of existing EXT

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#25]
Can you please change the actual version of this extension in the DEV plattform V8 to the following:

![grafik](https://user-images.githubusercontent.com/17588253/27643672-f769d990-5c21-11e7-8d73-23518f73bf89.png)

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

#Changing Version of existing EXT
**Status**: Done
**Screenshot**: http://prntscr.com/fs8i8c

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

that is ok. Thanks.

Regards,
Angelo
