### ISSUE TITLE
Bug: Clearing the cache in BE gets empty results 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#26]
Hello Jignesh

if you empty the cache in the BE of the DEV plattform some fields gets empty in the FE.

![grafik](https://user-images.githubusercontent.com/17588253/27674434-12eaab52-5ca6-11e7-9811-e7f474b5215a.png)

![grafik](https://user-images.githubusercontent.com/17588253/27674461-27886036-5ca6-11e7-8a01-44f254ed2bb5.png)

**Remarks:** 
Suddenly it appears and after a while it DISAPPEARS again after cleaning the Cache in the BE.

Can you please fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

#Issue with fields
**Status**: Done
**Comment**: We have resolved this. Can you please review this from your end too?

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

this seems now to work.

Was there any problem before? I ask because if we cleared all Caches in the TPYO3 the results gets disappeard...

Thanks.

Regard,s
Angelo.
