### ISSUE TITLE
Sorting fields in the BE

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#27]
Hello Jignesh

in the BE there is no sorting options for sorting single items. This concerns the whole view in the BE.
Can you please add or fix this?

Currently (example)
![grafik](https://user-images.githubusercontent.com/17588253/27674586-a962dbe0-5ca6-11e7-8362-3e5cccfa2a38.png)

Must have sorting options like this:
![grafik](https://user-images.githubusercontent.com/17588253/27674822-9e099c10-5ca7-11e7-91b3-5b5b39cac243.png)

Must have on every of this list views in BE:

Beschluss 	
Beschwerdetyp 
Bestimmung/Absatz 
Bestimmung  	
Entscheid-Dokument 
Keywords	
Medien	
Recht 	
Sender 	
Sendung 
Sprache 

Thanks for your work.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Screenshot**: http://prntscr.com/fs8ule

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks. Great. BUT this sorting option now MUST work also be shown in the single items of the whole Flexforms in the whole BE on every fileds. Can you please adapt this?

![screenshot_2](https://user-images.githubusercontent.com/17588253/28006260-d3e059d2-654e-11e7-90f0-546564347181.png)
  
![unbenannt-1](https://user-images.githubusercontent.com/17588253/28006264-d70851aa-654e-11e7-9757-3b0959ae273f.jpg)

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status**: Done
**Comment**: Please check now both will work as per your expectation.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

great. It works. Thanks.

Regards,
Angelo
