### ISSUE TITLE
Bug: Sorting view wrong

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#28]
Hello Jignesh

the FE in the filter has a wrong sorting view in all languages DE FR IT EN:

![grafik](https://user-images.githubusercontent.com/17588253/27675712-5611a570-5cab-11e7-9d50-a758ca2a4015.png)

It should should be sorted by artikel_de. Currently it gets sorted by ..we don't know....

Thanks for fixing that.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

We have checked this issue, The current order is already set on the "artikel_de" field with "Ascending" order. But, Here if you look on the field's characters there are some natural number in the beginning too. See this screenshot, Front End: http://prntscr.com/fs8loz Back End: http://prntscr.com/fs8m2t
So by default, it sorted with these characters too. That's why it looks like the wrong order. 
If you need to check then you can put all the title in a single array and can apply a sorting function. You will get the same result.

See this screenshot: http://prntscr.com/fs8mo0 from the script.

Please let's know your views here.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

please sort the results like this:
1.) Due to every item in the DB field has as beginning a "Art. xx" please add a 0 (Zero) on each one element and sort it like this. 

Example: If there is a item like Art. 1 Geltungsbereich add for the sorting a non visible 0 (Zero) with PHP for numbers below 10 after the dot of the Art. => So for the sorting it will be like this "Art. 01 Geltungsbereich". Like this the sortings gets correct showed like it must be.

The reson is that currently the sorting isn't correct shown on the website. It has to be sorted like this IN THE BACKGROUND for example:

Art. 01 Geltungsbereich
Art. 03 Auftrag
Art. 10 Kulturelle Ziele
a.s.o.

(this is just an example how in the background it has to be sorted with SQL. The additional 0 (Zero) MUST NOT be showed on the FE.)

Thanks for your work.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

We have gone through your last comment, It seems, technically not possible to manage the string dynamically. We can not manage the '0' only dynamically in the string for sorting.

If you want to have the string with the Ascending order then you should separate both the string with two fields separately, For e.g. http://prntscr.com/fvj7mm What do you think? please share your views here.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

well, I don't know why you could not do this, because due to every item in the field "bestimmung" it is starting with "Art. xx...." it must be possible to add dynamicly with PHP a function that checks always on the left part of the item of this field, if there is a number or not. If there is just one character then you should add an additional 0 (Zero) for sorting those fileds in the FE.

Can you please REcheck this issue? It should be possible. At least, I did it once some years ago with ASP VBscript and it worked. It is a quite "tricky" SQL, but possible.

Thanks.

Reagrds,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thank you for your message.

Yes, sure. We will check this again and get back to you.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

#Sort order
**Status**: Done
**Screenshot**: http://prntscr.com/fx26pj

**Note**: We have spent 1 Hour on this. Can you please confirm from your end?

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

You sent me a printscreen of just a part of the new sorted fields. BUT if you scroll down, you will see that after some records (beginning from Art. 57) the sortings aren't correct anymore. 

See http://prntscr.com/fx3cik 

The one hour until now are ok from our side.

Can you fix it that?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Greetings of the day!

Yes, we have checked this. It seems some records have some bad values which prevent it for the correct sorting. For this, you have to follow below steps.

1. Find the bad sorted record in backend - http://prntscr.com/fxy6cp, http://prntscr.com/fxy6gw
2. Edit it and remove the left part of 'artikel de' field - http://prntscr.com/fxy6q4, http://prntscr.com/fxy6tz
3. Add that left part again - http://prntscr.com/fxy735
4. See the FE - http://prntscr.com/fxy7b2
5. http://prntscr.com/fxy7en

Let's know your reply for the same.

Regards.

**Comment by angeloprevitali** [comment]
Good morning Jignesh

thank you very much for your feedback and message. We will test this.

Just one last question: Why do we have to delete and RE-Insert the data you explained? Is there any wrong thing in the DB or what is the reason?

Thanks for your quick feedback.

Wish you a nice day!

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your reply.

#Question
No, There is not any issue with the DB. This is just to prevent the extra process of the saving the field. So, if the date is not changed and remained the same as it's before so we don't need to do extra process.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

we still do not know HOW it is possible, that after REsaving this fileds it will work... But anyway: It works and that's the goal.

Thanks.

Regards,
Angelo
