### ISSUE TITLE
Bug: Language output wrong in filter view "Bestimmung"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#29]
Hello Jignesh

the output of the list view in the filter in the language FR, IT and EN is wrong. It should come the french language from the field artikel_fr.

![grafik](https://user-images.githubusercontent.com/17588253/27677351-9d84e362-5cb1-11e7-8170-ce52cf448a0b.png)

![grafik](https://user-images.githubusercontent.com/17588253/27677380-c088577c-5cb1-11e7-81b5-489e238b1386.png)

![grafik](https://user-images.githubusercontent.com/17588253/27677416-dfd790de-5cb1-11e7-819b-a60666495066.png)

Please keep in mind the sorting options as described in issue https://github.com/NetConsultAG/netc_ubidb/issues/28

Thanks for fixing that.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

**Status**: Done
**Screenshot**: http://prntscr.com/fs8uzq, http://prntscr.com/fs8v3r

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

our fault: EN is a error from our side. Forget about this. EN is not supported, that is correct.

Regards,
Angelo
