### ISSUE TITLE
Install Tool: Tables has to be cleaned up

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#3]
If you call up the install tool there are a lot of database which wants to be updated. This shouldn't be. Can you fix this?

See printscreen.

![screenshot_4](https://cloud.githubusercontent.com/assets/17588253/22646273/c6b76496-ec6b-11e6-83d7-72a05bffc8e2.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Comment: There are no DB changes needed in our extension. So this is maybe some other issue. Maybe a TYPO3 find ext_tables.sql file updated so it is showing changes.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
In the Install Tool TYPO3 says that the fileds are wrong. It MUST have the EXT:netc_ubidb extension. Please check the update script in the printscreen what TYPO3 wants to change for better debugging.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prntscr.com/e5yloa

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Perfect, thanks. Works.

Regards,
Angelo
