### ISSUE TITLE
Bug: Output in EN in FE in filter view is empty

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#30]
Dear Jignesh

on the EN page the FE is missing the pulldown with the "decisions" to choose in the filter form.

![grafik](https://user-images.githubusercontent.com/17588253/27677569-7c652b82-5cb2-11e7-9a9c-3d41538c2ab7.png)

Can you fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Let me try to explain here, As you know we are not following the default translation behavior for the records. We are managing all translations through fields, See this screenshot: http://prntscr.com/fs8ys2
As from the screenshot, It seems initially we have only 3 language fields. But now you have added the English language. So we have to add a field for English version too.

Fyi, If we go with default translation methods then we don't face such kind of problems while we introduce a new language. If we still go with the current structure then in future if we add any new language then the same problem might occur. 

Please advice your views here.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

EN is not supported, that is correct. Our fault. Sorry. You are absolutely right.

I close this issue.

Reagrds,
Angelo
