### ISSUE TITLE
Bug: Sorting items in FR, IT and EN language in filter view "keyword" are wrong. 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#31]
Hello Jignesh

the list view in FE in the filter in FR and IT are wrong. Can you please sort the output by alphabetical order A-Z. In the EN language the whole output is completely empty

![grafik](https://user-images.githubusercontent.com/17588253/27677887-89fac490-5cb3-11e7-9fdb-8edaf2ecb793.png)

![grafik](https://user-images.githubusercontent.com/17588253/27677957-c0c98cae-5cb3-11e7-8de8-d55ea141ee22.png)

![grafik](https://user-images.githubusercontent.com/17588253/27678020-eda979dc-5cb3-11e7-8719-3b54d11231c5.png)

Thanks for fixing that.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

As I have mentioned here: #30 We are not following the default translation behavior.

Now, In this particular issue, The field is sorted with the default field which is DE language. So all fields are showing with sorting on DE language. 
We can add a condition with specific language for such kind of problem, But in the future, if you introduce any new language then we have to add a new condition for the new language.

Please guide us with your views.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

ok, on the FR language the output is now coming. Thanks.

We can close this issue.

Regards,
Angelo
