### ISSUE TITLE
Bug: Empty values in FE in language EN in filter view on "medium"

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#32]
Hello Jignesh

the output in EN in filter view of "medium" in EN is empty. 

![grafik](https://user-images.githubusercontent.com/17588253/27678149-7b3f1fe0-5cb4-11e7-82f8-d1e1ea111e18.png)

Can you fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

This is the same issue as I have mentioned here #30 

So, please guide us more with your views.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

You are absolutely right: there is NO EN language. Out fault. 

We can close this issue.

Regards,
Angelo
