### ISSUE TITLE
Change Request: Adapting sorting options in BE fields

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#33]
Hello Jignesh

this is a change request and the work for this can be billed due it is a change request of our customer.

Could you please adapt the BE form list view of the fields showed in printscreen that there are showed ONLY items which are marked as "active" (active status of TYPO3) AND where tx_netcubidb_domain_model_bestimmung.used = "1".

![screenshot_1](https://user-images.githubusercontent.com/17588253/28270895-56f33912-6b07-11e7-902a-4aa226481c99.png)

Thanks for your work.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message. Let's check this, We will get back to you soon.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

**Status**: Done
**Screenshot**: http://prntscr.com/fxy7vm

**Note**: We have spent 1 Hour on this task. Can you please confirm from your end too.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

we checked this and it seems to work, thanks.

The additional 1 hour for this work are ok.

Regards,
Angelo
