### ISSUE TITLE
Bug: Sorting view in FE 

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#34]
In the FE sorting view there is now missing a part that was correctly displayed before:
The fields “recht_de/recht_fr/recht_it“ from the table "tx_netcubidb_domain_model_recht" are not displayed anymore. See the picture below, the texts in the red square are not displayed anymore:

<img width="462" alt="screen shot 2017-08-04 at 09 31 28" src="https://user-images.githubusercontent.com/1160557/28958784-fe3e7846-78f7-11e7-9bc9-6b26478dbd76.png">

Is it possible for you to fix this until the middle of next week? If not let me know until when you can do it. Thank you!

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 13. August 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 14. August 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Michel Rossier (michel.rossier@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by michelrossier** [comment]
Hello
Can you give us a status update on this issue or when it can be finished? I asked in the initial message if it can be done by the middle of this week, which is now, but haven't gotten a feedback if you actually have time or not. Any feedback is appreciated. Thank you.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

**Status**: Done
**Screenshot**: http://nimb.ws/bsWGRP

Regards.

**Comment by michelrossier** [comment]
Hello @jigneshnitsan 

Thank you, that is perfect!

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis voraussichtlich bis Ende September 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet.

In dringenden Fällen kontaktieren Sie Herr Michel Rossier (michel.rossier@netconsult.ch, Tel.  031 352 00 88) oder Herr Bruno Buess (buess@netconsult.ch, Tel.  031 352 00 88).

Besten Dank.


Freundliche Grüsse
Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch
