### ISSUE TITLE
When selecting a category under "Bestimmung" no entries are shown

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#36]
Hi @jigneshnitsan 

Our developer provided me with this feedback:

When you chose a category under "Bestimmung" on this page:
http://dev.kommissionv8.netconsult.ch/index.php?id=209

Then no results are returned.

But the following results should be returned:
Example 1:
If you chose for example  "RTVG, Art. 94 Beschwerdebefugnis" then the at least the entry "b.748" should be displayed.

Example 2:
If you chose "EÜGF, Art. 11 Allgemeine Normen" then at least the entries "b.487" and "b.371" should be displayed.

**But in all cases no results are shown.**

**Can you fix this bug until Wednesday next week?** These delays are becoming a big problem for us.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

We need to discuss this issue. We have already left a message on the Skype group. Can you please let's know your availability so we can discuss this with you?

Awaiting for your reply here.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Greetings of the day!

**Status**: Done
**Screenshot**: https://prnt.sc/gneskn

Please review this and let's know your reply for this.

Regards.

**Comment by michelrossier** [comment]
Thank you @jigneshnitsan I've got a positive feedback, this is okay and done. Thanks!
