### ISSUE TITLE
Link not localized in detail view

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#38]
We have another bug report:

This is similar to the issue here: https://github.com/NetConsultAG/netc_ubidb/issues/37#issuecomment-336789556

## Problem: 
The link in the detail view of the search results does not lozalize the icon (as mentioned in the the last issue ticket) but also, the link to the PDF (b.748 ) is not localized either in other languages than german:

### German example (OK, b.748 is linked correctly to the PDF)
http://dev.kommissionv8.netconsult.ch/de/ubi-datenbank/ubi-db-details/?tx_netcubidb_documents%5Bdokument%5D=746&tx_netcubidb_documents%5Baction%5D=show&tx_netcubidb_documents%5Bcontroller%5D=Dokument&cHash=08ab330a7d1327902df14526af4502d5

### French example (b.748 is not linked with its language variant)
http://dev.kommissionv8.netconsult.ch/fr/ubi-datenbank/ubi-datenbank/?tx_netcubidb_documents%5Bdokument%5D=746&tx_netcubidb_documents%5Baction%5D=show&tx_netcubidb_documents%5Bcontroller%5D=Dokument&cHash=08ab330a7d1327902df14526af4502d5

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

**Status**: Done
**Screenshots**: https://prnt.sc/gy15s0, https://prnt.sc/gy164y, https://prnt.sc/gy16i2

**Note**: We have spent 1 Hour on this task. Please confirm

Regards.

**Comment by michelrossier** [comment]
Hello @jigneshnitsan 

Thank you, now it is almost perfect.

The link is as it should be now. But the text in the text inside the "( )" should not be localized:

See: The text (fr, pdf) should be (de, pdf) everywhere:
<img width="588" alt="screen shot 2017-10-17 at 09 08 12" src="https://user-images.githubusercontent.com/1160557/31651168-ddf134c2-b31a-11e7-8aa5-f2ff420e7271.png">

Why? Because it is defined here at "Sprache" (the setting at the bottom):

<img width="1112" alt="screen shot 2017-10-17 at 09 07 01" src="https://user-images.githubusercontent.com/1160557/31651113-a51ce9de-b31a-11e7-9d1d-92bcfb7540b2.png">

That means the text with the "de" inside the "( )" should stay "de" (and not be localized) because in the entry it is defined as "de" for the document (that is the language of the document and it won't change). That means it has to appear as "de" even on french or english etc.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Greetings of the day!

Thank you for your message.

Unfortunately, we don't have enough time to work on your last feedback. As you know we have been in Diwali holidays up-to 23rd October. We will work on it after our Diwali vacation.

Have a nice day and a great week ahead.
Regards.

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 
Thanks for your feedback. 

I wish you a happy Diwali!

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Good Morning!

I hope you are doing good.

**Status**: Done
**Screenshots**: https://prnt.sc/h1o1rx, https://prnt.sc/h1o1vx, https://prnt.sc/h1o20o

Let's know if you have any point for us.

Regards.

**Comment by michelrossier** [comment]
Hi @jigneshnitsan 
I've got this feedback:

The implementation is not correct. In this message https://github.com/NetConsultAG/netc_ubidb/issues/38#issuecomment-337139344 I specified that the language is defined by the setting in the second screenshot. 

## Problem
But now it turns out that on every document it is written "de" as if it was hardcoded. For example document b.743 is a french document, that means the text has to be "fr" (also on translated pages) and not "de" as it is now:

## Example:
### In the backend it is defined as "fr":
![language-document](https://user-images.githubusercontent.com/1160557/32095310-024a7f32-bb03-11e7-87a9-0b72c8204357.png)

### But in the frontend it is shown as "de":
![language-frontend](https://user-images.githubusercontent.com/1160557/32095344-18ee4ec6-bb03-11e7-8fea-1aa5f4e17bc3.png)

## Solution
Take the value from the "Sprache" field that is defined in the backend and display it on the frontend (also on the translated pages)

**Comment by michelrossier** [comment]
Hello @jigneshnitsan
Do you have an approximate estimation when you can work on this issue?

For us this is still very urgent, as the customer wants to go live.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 
Greetings of the day!

**Status**: Done
**Comment**: Now,  the value from the "Sprache" field that is defined in the backend and displays it on the frontend (also on the translated pages) 
**Screenshots**: https://prnt.sc/h306qy, https://prnt.sc/h306vx, https://prnt.sc/h3070l, https://prnt.sc/h307dn

Please review this from your end.

Regards.

**Comment by michelrossier** [comment]
That is perfect, thank you very much!
