### ISSUE TITLE
UTL links not localized

### ISSUE THREAD

**Issue by michelrossier** [NetConsultAG/netc_ubidb#39]
Hi, I've got the following feedback:

The links on the detail pages are not localized, see example here in the red area:
![pic1](https://user-images.githubusercontent.com/1160557/32161966-afc05f3c-bd57-11e7-87d8-0736a577c2e1.png)

For these links you should display the contents inside the fields of the columns "url_fr", respectively "url_it" of the table "tx_netcubidb_domain_model_rechte":

![pic2](https://user-images.githubusercontent.com/1160557/32162046-e476f2fe-bd57-11e7-93ec-2882e6a3c06f.png)

Currently only the german links are displayed in all translations.

**Comment by michelrossier** [comment]
Hello @jigneshnitsan 
Do you have an approximate estimation when you can work on this issue?

For us this is still very urgent, as the customer wants to go live.

**Comment by jigneshnitsan** [comment]
Hello @michelrossier 

**Status**: Done
**Screenshot-It**: http://prntscr.com/h5a2no
**Screenshot-Fr**: http://prntscr.com/h5a33x
**Screenshot-DE**: http://prntscr.com/h5a3qm

Regards.

**Comment by michelrossier** [comment]
Thank you @jigneshnitsan that is perfect now!
