### ISSUE TITLE
Details page not working and has error by calling up details page if no value is sent

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#4]
In the manual you sent us there is written, that you have to insert a Plug-In for the list and and we have to configure it which detail page gets the results. https://docs.google.com/document/d/1FsGqozjVZRpLo6lemJKLPpudVf_TMgVHALJY3rF7eyE/edit. In the current configuration it wasn't set upped like this. Can you please fix this bug that it works like described in your manual? One PlugIn for listings and one Plugin on a different page for details view.

Plus, if you call up the details page without having any value there is an error. Can you please add a XLF in all languages DE/FR/IT/EN that we can translate, if this error occures?

![screenshot_5](https://cloud.githubusercontent.com/assets/17588253/22646386/7130c200-ec6c-11e6-9bc3-f680155dd8f9.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Comment: We have placed massage if value not found - http://prntscr.com/e5i4j7

Regards.

**Comment by angeloprevitali** [comment]
Works, ok.
Thanks.
