### ISSUE TITLE
Filtering in frontend ignores some values

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#40]
Hello Jignesh

we found a but in the FE in the filtering.

Situation: By filtering (checked different checkboxes in the FE) with multiple selections of **every single category** like **"Medien", "Veranstalter", "Sendung/Publikation", "Bestimmung", "Schlüsselwort"** the results get currently ONLY of the **FIRST item saved in the database**. All other entries, which are saved in the database gets **IGNORED**.

**_Example:_**

By filtering one of "Bestimmungen" which is checked for filtering 

![grafik](https://user-images.githubusercontent.com/17588253/34104352-625dc0ee-e3f0-11e7-85de-871e00c86339.png)

the value of this item is in example 96.

Now the result page show ONLY results from entries where this value leads on the BEGINNING in the table of the mySQL database. **If** now this value (i.e. 94) leads AFTER a comma separated value in the database this item will be NOT shown.

![unbenannt-3](https://user-images.githubusercontent.com/17588253/34104586-5b2d147c-e3f1-11e7-881a-ec0d4ed4f1fd.png)
 
Example: 
a.) If the query search for this value in the searches the corresponding ID will be **NOT** shown in the results!
b.)  If the query search for this value in the searches the corresponding ID will be correctly shown in the results!
c.) If the query search for this value in the searches the corresponding ID will be correctly shown in the results!
d.) If the query search for this value in the searches the corresponding ID will be **NOT** shown in the results!

This concerns ALL the single items of all the categories which you can choose.
If you got questions about this bug, please SKYPE me and we can clear out.

Until when can you fix this? Please do the changes on the DEV server which leads on http://dev.kommissionv8.netconsult.ch and **DO NOT** Upload anything else on GitHub. Please let me know additionaly which files you modified after that. Like this we can better understand this extension.

Thanks for your quick help and work!

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Greetings of the day!

We have resolved the issue.

Status: Done
Screenshots:
**Medien**
Screenshot: https://prnt.sc/hphomb, https://prnt.sc/hphp1m

**Veranstalter**
Screenshot:  https://prnt.sc/hphntz, https://prnt.sc/hphnnr

**Sendung/Publikation** 
Screenshot: https://prnt.sc/hphqoy, https://prnt.sc/hphqu0

**Bestimmung**
Screenshot: https://prnt.sc/hphdwx, https://prnt.sc/hphehf

**Schlüsselwort**
Screenshot: https://prnt.sc/hphsn7, https://prnt.sc/hphsh5

Please review this on your end and let's know if still faces any issues on this.

Regards.

**Comment by angeloprevitali** [comment]
Good morning Jignesh
Thank you for your fixes. We will check it and give you feedback.
Best regards,
Angelo

**Comment by angeloprevitali** [comment]
Dear Jignesh

we checkt it and everything works as it should: -) 

Great work. Thanks.

Best regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thank you for your confirmation.

I just want to confirm our efforts hours. As you know this extension/project has already passed the support period. So, can you please confirm **2 Hours** for this for our efforts (Actually, we have spent more than **4 Hours**) to resolve this bug?
Here waiting for your confirmation.
Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh
YES, I can confirm this 2 hours for adapting this.
Thanks.
Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you very much for your confirmation.

Have a nice day ahead.
Regards.
