### ISSUE TITLE
FE: Filtering not working correctly completely

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#5]
The filtering of the frontend is not working completely. A filtering must search over the single criterias choosed in the filters.

- Filtering by Year: This one works corretly (This works, OK)

- Filtering with "Medium" gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all. 

- Filtering with "Versanstalter" gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all. 

- Filtering with "Sendung "gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all. 

- Filtering with "Bestimmung" gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all. 

- Filtering with critera "Beschluss" gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all.

- Filtering with "Schlüsselwort" gets ignored by search results (you should choose from "Alle" (all) or single item or multiple checkboxes choosed for filtering). It seems to have no effect at all. 

- Search function is not working. It must search with the filtering options choosed.

- Sorting option (Sortieren nach ) after submitting filter is not working. After getting the results and apllying the sorting options nothing is showed anymore. Mostly if you add some search text in the search field. It must sort the results by filtering with the criterias choosed AND the single sorting options, too.

Can you please fix this issues?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Status: Done
Screencast: http://recordit.co/lM905kJ5bT
Comment: We have corrected the checkbox selection issue, But, the filter is already working perfectly. Can you please test it from your end again?

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
I saw your movie. Thanks. But you just tested the filter with the filter "Medien" in your movie. Try to filter multiple filters like different filters together and not only from the filter "Medium".

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thank you for your reply.

Please find our update as following.

#Try to filter multiple filters like different filters together and not only from the filter "Medium"
Status:  Done
Screencast: http://recordit.co/brIlRhWevG

Regards.

**Comment by angeloprevitali** [comment]
The filtering is working now, thanks. BUT if you enter an additional text in the search field there were no results anymore. You MUST find results in the free test search for ALL ITEMS that are stored in the extension, too. That means in your demo movie you MUST find also ALL results with the single items. for example if you just search for internet in the search field you must find all entries that are in the category MEDIUM > Internet, if you search for  arte, you must find all results that are associated with the filter VERANSTALTER > Arte ans so on for all.

![unbenannt-2](https://cloud.githubusercontent.com/assets/17588253/22740941/d029718e-ee11-11e6-9405-f326cd828842.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Please find our comment as following.

We were thinking that you want to search in all non-relational fields only. So we had implemented it as it. But from your this description, we are confused with one point.
 
**Confusion**:
Do you want to search in all fields of all tables of the extension, or only the fields used for the showing in Frontend? Please send the list of table > field to search in if you want specific search. It may be hardcode to make a search in all columns of all tables, this may affect the other filter option conditions.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

I see your point. but as in the specs described you have to be able to search in all char- and text fields as well. I created you a PDF that let's you show which fields should be found by searching in the search fields togheter with the existing filtering.

[searchaeble-fields.pdf](https://github.com/NetConsultAG/netc_ubidb/files/774264/searchaeble-fields.pdf)

Hope it help.

Otherwise please let me know :)

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message.

We have tried to add all given fields in the search query.  But it seems the amount of query and the complexity is too much for getting the result. Therefore we have to add too many conditions in SQL query which leads to improper results.
 
I have attached a document carrying the SQL query which generates when we have only use the search box from a whole filter.

Can you please help us here to determine the perfect effective query?

[NETC_ubidb.zip](https://github.com/NetConsultAG/netc_ubidb/files/779596/NETC_ubidb.zip)

Thanks in advance for your help

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

I hope you are doing good.

Have you got a chance to check our last comment? Please let's know your feedback on the same.  Regards!

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Mittwoch, 22. Februar 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Donnerstag, 23. Januar 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Ernest Peter (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
Good morning

we asked our customer concerning this issue. But we did not get any answer, yet. As soon we got the answer we will answer it to you.

Regards,
Angelo

**Comment by angeloprevitali** [comment]
Good morning Jignseh

we discussed the thing with our customer and we can keep the search asit is now. So I can close this task.

Regards,
Angelo
