### ISSUE TITLE
Filtering page FE: checkbox dependency wrong

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#6]
On the filter page the dependency is wrong: If you choose "Alle" (all) it should choose all (Alle). If you choose single items of a filter (or multiple ones) the checkbox "Alle" must disappear. Currently it seems to work in a very stringe way we do not know exactly. By choosing all (Alle) and another one in the listing the Alle disappears correctly. But after choosing another one AND Alle again every checkbox is checked (selected).

This inconsistency/Bug is on every filter with Medium, Versanstalter, Sendung, Bestimmung and Schlüsselwort.
 
Can you fix this? 

Thanks.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screencast: http://recordit.co/UVR2QFiHPG

Regards.

**Comment by angeloprevitali** [comment]
Just one word: Great!

It works. 

Thanks.

Regards,
Angelo
