### ISSUE TITLE
Different languages of pages has no results

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#7]
If you switch the page language to another TYPO3 CMS language there are no results displayed. The only language which works is DE (german).

http://dev.kommission.netconsult.ch/index.php?id=253&L=0 (ok, works perfect)
http://dev.kommission.netconsult.ch/index.php?id=253&L=1 (FR, there are NO data nowhere!)
http://dev.kommission.netconsult.ch/index.php?id=253&L=2 (IT, there are NO data nowhere!)
http://dev.kommission.netconsult.ch/index.php?id=253&L=3 (EN, there are NO data nowhere!)

On every language there must be shown the same content from the database as described in specs.

Thanks for fixing it.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Please find our comments as following.

**Problem**: The Medien Icon image is not coming because you have set config.sys_language_mode = strict in TypoScript, and in this custom extension records are not translatable, So TYPO3 can't fetch Icon image.

**Solution/Recommendation:**
Change TypoScript setting to config.sys_language_mode = content_fallback for the pages where extension is loaded.

So can we change these settings in order to get the result? Please let's know your reply for the same.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks for your information. I added this lines in TS:
```
// keep config as is but make exeption for the two FE pages with fallback
[globalVar = TSFE:id = 253, TSFE:id = 257]
config.sys_language_mode =  content_fallback ; 0
[global]
```
We have to keep the whole website keeping it with config.sys_language_mode = strict.

Those should do the work, right? Is this correct? 

**Question**
I am wondering: With or without this lines there is always an output on the website. Why?

Thanks for your feedback.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

Please find our comment as following.

**#Without this setting:** 
Listing and all things will work perfectly without this settings, but the images and files uploaded are using FAL method, so if you make language mode = strict, it will find the localization of the FAL records and if it not found then returns NULL.

**#With settings:** 
The issue about FAL records finding localization records of FAL will return NULL, the setting change to language mode = content_fallback, will check localize record first, but if a query doesn't return any localization of the main FAL record, then the default language relation record will be fetched.

**#In our case:** 
While fetching medium icon and uploaded documents, TYPO3 was going to find the FAL relation with the current language of the FE, and if it doesn't find the current language record it was returning null, so we can't see those images in FE with non-default languages. So the settings are used for that reason.

Don't hesitate to ask if you have any furthermore queries.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Ok. Thanks for your feedback.

As the page in alle TYPO3-languages are displayed correctly like they should I will close this ticket now.

Regards,
Angelo
