### ISSUE TITLE
BE fields are not completly showed on FE

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#8]
On the field Bestimmung the saved item with texts in the BE are longer then showed in FE. See printscreen. It seems as after a comma the text on the FE gets "cutted". 

Can you fix this? Thx.

![screen-shot4](https://cloud.githubusercontent.com/assets/17588253/22738785/23d467ac-ee09-11e6-9dc9-b7a34a25ca68.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thank you for your message.

Actually, as per the specification document, 
In BE we have shown the values from tx_netcubidb_domain_model_best_absatz table values, but we have seen that there are multiple bestimmung items selected for different absatz (http://awesomescreenshot.com/0a468ner6d) so the select box shows them many times and we found this confusing. So we have put the absatz field value with comma separation - http://awesomescreenshot.com/00f68neofa. 

And for FE the checkboxes are from the tx_netcubidb_domain_model_bestimmung table. 

So can you please give us more information on this? Thanks!

**Comment by angeloprevitali** [comment]
Hello Jignesh

my fault, sorry. You did it correctly. I was wrong.
You can let it be as it is. Like this it is correct.

Regards,
Angelo
