### ISSUE TITLE
Fields "Beschwerdetyp" and "Beschluss" in BE must be mandatory

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_ubidb#9]
In the BE the fileds as Pulldown must be mandatory as described in the specs. Currently you can save a new item without choosing one of this field. See printscreen.

![screen-shot5](https://cloud.githubusercontent.com/assets/17588253/22738916/c75038de-ee09-11e6-9cb0-da195b391b68.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/17588253/22738938/de899a2c-ee09-11e6-9074-015f4df5ec12.png)

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have checked this issue, It seems the validation is working correctly in 7.X and 8.X  Please see this screenshot

![new typo3 site typo3 cms 7 6 14](https://cloud.githubusercontent.com/assets/14850299/22926218/b3957224-f2d1-11e6-8493-806dc06e47d9.png)

It seems it's not working on the 6.X So there might be two options.

1. Remove blank option and set first value as default selected
2. Change control type to the multi-select box allowing only one selection.

**Note:** As you will migrate the site into the 7.x.x and 8.x.x, we don't need to do anything as it is already working in those versions.

Please share your reply with us.
Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

this one has to completely work like explained. So on the TYPO3 version 6.2 the initla value mus be emtpy and checked. There MUST be a validation for this field. 

We saw that currently the initial value is empty. As possible solution for this you could try to do it like this: Try to set an inital value of the empty first field and then if you want to save the TYPO3 should check if the value is bigger then 0 for example.

Further i think that on a flexform there are validation settings for select fields you could use like

`'minitems` => 0',` and/or
`maxitems => 1`

So, this feature MUST work in a way with the version 6.2.

Thanks for finding a solution.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Thank you for your message.

We have tried all possibilities here.

We have checked all possible values like ('', 0, NULL) etc. We think you have to look into these issues indicating that 'eval' validations are not made for a select box in TYPO3 6.2.x version.
https://forge.typo3.org/issues/60908
https://forge.typo3.org/issues/60247

Here may be a proposed Solution for 6.2.x is,  They suggested using a multi-select box for making it required.
 
Note: Just a question for you. If we are already moving into next version, Then is it really important to go for this with old version of TYPO3?

Thank you in advance for your feedback.

Regards.

**Comment by angeloprevitali** [comment]
Hi Jignesh

ok. I discussed it with our project leader and we will go on like this:

Please keep the validation for 6.2 as it is and adapt it for 8.6^ with the dependencies.

Is that ok for you?

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your update.

Okay, That's fine with us.
So, It means we don't have to work on it. So you can close this ticket now. Regards!

**Comment by angeloprevitali** [comment]
Hello Jignesh

so, does this thing already works as described below on the TYPO3 CMS verison 8.6?

Thanks for your feedback.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

It's also working with TYPO3 8.6 Please check this screenshot: http://prntscr.com/edtq65

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

i installed the EXT on a TYPO3 8.6 on t8.edorf.ch and I got a big error by installing the whole extension.

So this EXT seems not to be compatible with 8.6 yet.

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/23355408/d67de8da-fcd5-11e6-8453-09b968f38cb3.png)


Can you please fix this?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

#Error by installing extension
**Status**: Done
**URL**: http://t8.edorf.ch/de/startseite/

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Thanks. Works.

Great.

Regards,
Angelo
